[package]
name = "mine"
version = "0.1.0"
authors = ["Andrei Popa <andreipopa0498@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.8.1"
hex-literal = "0.2.1"
hex = "0.4.2"
rayon = "1.3.0"